
.PHONY: all
all: microasm intel_hex_generator hex2mem

microasm: microasm.c

intel_hex_generator: intel_hex_generator.cpp

hex2mem: hex2mem.c

.PHONY: clean
clean:
	rm microasm intel_hex_generator hex2mem